DROP TABLE IF EXISTS packing_list_items CASCADE;

DROP TABLE IF EXISTS packing_lists CASCADE;

DROP TABLE IF EXISTS template_items CASCADE;

DROP TABLE IF EXISTS templates CASCADE;

DROP TABLE IF EXISTS items CASCADE;

DROP TABLE IF EXISTS categories CASCADE;

DROP TABLE IF EXISTS users CASCADE;